FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /srv/hyfuzz

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY config ./config
COPY scripts ./scripts
COPY VERSION ./VERSION

CMD ["python", "-m", "src"]
